### ISSUE TITLE
Incorrect parsing of triple-backtick code block newlines

### ISSUE THREAD

**Issue by gordrs** [RickStrahl/Westwind.AspNetCore.Markdown#21] opened 2020-08-12 09:04 UTC
Greetings,

I've noticed an issue when it comes to new lines and triple-backtick code blocks not parsing correctly. When one has newlines within the code block, new `<pre><code>` tags are inserted in its place.

Markdown
```
#### Markdown parsing problem example

```csharp
namespace MyNamespace
{
  private readonly ICustomInjectedInterface _customInjectedInterface;
  public class MyClass
  {
    public MyClass(ICustomInjectedInterface customInjectedInterface)
    {
      // Below this is a blank line

      _customInjectedInterface = customInjectedInterface;
    }
  }
}
```
(there are closing triple backticks, but it appears even github is not immune to parsing issues)

Resulting HTML
```
<h4 id="markdown-parsing-problem-example">Markdown parsing problem example</h4>
<pre><code class="language-csharp">namespace MyNamespace
{
  private readonly ICustomInjectedInterface _customInjectedInterface;
  public class MyClass
  {
    public MyClass(ICustomInjectedInterface customInjectedInterface)
    {
      // Below this is a blank line
<pre><code>  _customInjectedInterface = customInjectedInterface;
}
</code></pre>
<p>}
}
</code></pre>
```

Rendered page
![image](https://user-images.githubusercontent.com/6892487/89996808-29e63280-dc83-11ea-8f29-af89e362039a.png)

**Comment by RickStrahl** [comment] 2020-12-30 22:30
Sorry for the late response - I thought I had replied here (I know I wrote it out but perhaps forgot to send).

Blank spaces in code blocks should not be a problem. 

The problem is not the blank line, but the fact that you're nesting a code blocks inside of a Markdown Code block. This means you open the markdown code block and close it on the nested code block. The behavior we see here on GitHub is really odd - it looks like it's actually picking up the nested code block but does so incorrectly terminating both at the end of the nested block.

Anyway - this is invalid Markdown and that's why it's not working.

There's specific syntax that you can use to nest Markdown by using 4 backticks for the *wrapping* code block.

I can't post an example because that would require wrapping yet one more time :smile: but here is what the result looks like:

````markdown

This is code

```cs
int x = 1;

x++;

return x;
```

More text

````

**Closed as completed** 2020-12-30 22:30 UTC
